sudo: required
services:
  - docker

before_install:
  - docker build -t rubenberna/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rubenberna/react-test npm run test -- --coverage

after_success:
  - docker build -t rubenberna/multi-nginx ./nginx
  - docker build -t rubenberna/multi-server ./server
  - docker build -t rubenberna/multi-worker ./worker
  - docker build -t rubenberna/multi-client ./client
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to Docker Hub
  - docker push rubenberna/multi-nginx
  - docker push rubenberna/multi-server
  - docker push rubenberna/multi-worker
  - docker push rubenberna/multi-client

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-container"
  env: "MultiContainer-env"
  bucket_name: "elasticbeanstalk-eu-west-1-305799247952"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
